# Generated by Django 5.2.3 on 2025-07-01 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('telephone', models.IntegerField()),
                ('adresse', models.CharField(max_length=40)),
                ('heure_ouverture', models.TimeField()),
                ('heure_fermeture', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('plat_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(max_length=100)),
                ('photo_url', models.CharField(max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
        ),
    ]
