# Generated by Django 5.2.3 on 2025-07-03 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plat',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='plat',
            name='plat_id',
        ),
        migrations.RemoveField(
            model_name='plat',
            name='prix_unitaire',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='heure_fermeture',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='heure_ouverture',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_id',
        ),
        migrations.AddField(
            model_name='plat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='plat',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plat',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plat',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plats', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='adresse',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
