# Generated by Django 5.2.3 on 2025-07-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_plat_photo_url_remove_plat_plat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='plats_photos/'),
        ),
    ]
