# Generated by Django 5.2.3 on 2025-07-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='photo_restaurant',
            field=models.ImageField(blank=True, null=True, upload_to='plats_photos/'),
        ),
    ]
