# Generated by Django 5.2.3 on 2025-07-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_photo_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='horaires',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='photo_restaurant',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants_photos/'),
        ),
    ]
