# Generated by Django 5.2.3 on 2025-07-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_livreur_nom_livreur_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='cin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_livraison', 'En Livraison'), ('indisponible', 'Indisponible')], default='disponible', max_length=20),
        ),
    ]
