# Generated by Django 5.2.3 on 2025-07-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('adresse', models.CharField(max_length=60)),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('mot_passe', models.CharField(max_length=50)),
                ('nom_complet', models.CharField(max_length=35)),
            ],
        ),
    ]
