# Generated by Django 5.2.3 on 2025-07-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_loginclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('confirm_password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='loginclient',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
