# Generated by Django 5.2.3 on 2025-07-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_signupclient_alter_loginclient_password'),
        ('orders', '0002_alter_commande_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='LoginClient',
        ),
        migrations.AddField(
            model_name='signupclient',
            name='adresse',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='signupclient',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
