# Generated by Django 5.2.3 on 2025-07-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_delete_client_delete_loginclient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupclient',
            name='confirm_password',
        ),
    ]
