# Generated by Django 5.2.3 on 2025-07-14 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_signupclient_confirm_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupclient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='signupclient',
            name='password',
        ),
        migrations.RemoveField(
            model_name='signupclient',
            name='username',
        ),
        migrations.AddField(
            model_name='signupclient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
