# Generated by Django 5.2.3 on 2025-07-07 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_signupclient_alter_loginclient_password'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='clients.signupclient'),
        ),
    ]
