# Generated by Django 5.2.3 on 2025-07-15 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_remove_signupclient_email_and_more'),
        ('orders', '0003_remove_commande_client_commande_adresse_livraison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.signupclient'),
        ),
    ]
