# Generated by Django 5.2.3 on 2025-07-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_commande_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de livraison'), ('livree', 'Livrée')], default='en_attente', max_length=50),
        ),
    ]
